### ISSUE TITLE
Clarify the relationship between loops and async

### ISSUE THREAD

**Issue by teazean** [tc39/proposal-async-await#112]
After I did some experiments on chrome & node, I felt vaguely `await` is blocking the loops.
Only after reading #29 , I was pretty sure it was designed to be.
I think we can open a new chapter in the specification and clearly express this design between loops and `async/await`.

**Comment by teazean** [comment]
Maybe we could clearly express `await is blocking anything or something`.

**Comment by YowaiCoder** [comment]
of course it blocks.

**Comment by ljharb** [comment]
“Blocks” is the wrong term entirely since it surrenders to the event loop, but from the perspective of the `async function` in which `await` appears, it pauses that function until the Promise it’s awaiting settles.

The spec text for `await` as well as the conceptual model of the feature already expresses this interaction (not unique to loops, but to any language construct directly within an async function).

**Comment by teazean** [comment]
Yes, I can read it from [here](https://tc39.github.io/ecmascript-asyncawait/#abstract-ops-async-function-await).

Specification does not discuss implementation. `blocks` is so implemented.

Thanks for explaining, and I'm closing this issue.

**Comment by ljharb** [comment]
The spec definitely prevents any blocking, and discusses the promise job queue (which in browsers and node, is part of the event loop).
