### ISSUE TITLE
Possible to await non-promise synchronously?

### ISSUE THREAD

**Issue by jhusain** [tc39/proposal-async-await#33]
Is this legal?

await 1;

Furthermore can the expression above evaluate synchronously?

The answers to these questions impact  the asynchronous generator proposal. Ideally the answers would be "yes" and "yes" respectively. The reasoning is that we would like to be able to produce observables that respect back pressure like so...

for(x on xs) {
  await yield x + 5;
}

...without paying any performance cost in the event that the generator sink can process items synchronously (ie. next() does not return IterationResult<Promise> for each item it receives). 

Developers would be more likely to create event streams that respect back pressure if they did not have to commit to paying a performance cost regardless of whether the sink was synchronous. Note that when asynchronous I/O operations are performed, most of the time data is being inserted directly into a buffer synchronously. Forcing every item to be inserted into the buffer on a separate turn would be very expensive.

**Comment by domenic** [comment]
Yes and no. See previous issues for the latter.

Promises are designed not to take separate turns. Because of the microtask queue, once you pay the cost of unwinding the current stack (i.e. of one async operation), there is no further cost for multiple async operations since they just take place in a while loop.

>  Note that when asynchronous I/O operations are performed, most of the time data is being inserted directly into a buffer synchronously.

Citation needed. I have found the opposite to be true, in both epoll(7) + read(2) and fread(3)-based designs.

**Comment by jhusain** [comment]
Thanks for replying Domenic. Your point about the micro task scheduler is well taken, and the operation is indeed synchronous, but is it low cost? 

The naïve implementation would seem to allocate a new promise for every iteration. However if the only requirement is that await schedule on the micro task scheduler, it seems to me to be intuitively possible to reuse a single function for each iteration. Do you see any reason why this would not be possible? 

JH

**Comment by jhusain** [comment]
If this is the previous issue you are referring to (https://github.com/lukehoban/ecmascript-asyncawait/issues/22) I find the conclusion somewhat unsatisfactory and I have some additional questions. You claim that this optimization is unnecessary because most of the time the expression on the right-hand side of an await will be a promise. The asynchronous observable is a powerful counterpoint here. How is a data source to know in advance whether it will be processed synchronously or asynchronously?  It is always possible to buffer the data in the source, and there are circumstances in which this would happen other than asynchronous I/O.

Using a filesystem API on the browser, I could load data from disk and dump it directly into the DOM (effectively like a buffer) which would mean I could synchronously consume it. Otherwise I could dump data into another file, which would make it asynchronous. It is not reasonable to expect data producers to know how their sinks will use them. 

Asynchronous I always just want to use case, but it is an important one. While it might be the case that most network requests do not require a buffer,

**Comment by jhusain** [comment]
Sorry butterfingers. Continuing my thought...

Asynchronous I/O is just one use case, but it is an important one. Given your experience in this area, I'm inclined to believe you with regard to frequency of buffer writes during Async IO operations. You may indeed be right that most requests are served without using a buffer. However that does not mean that when buffer writes are necessary, the ability to do them quickly is not important. 

Kevin's performance numbers (outlined in the linked issue) demonstrate that scheduling Micro tasks in a tight loop can be very expensive. Can you give me an example in which executing an await synchronously would cause harm?

**Comment by domenic** [comment]
> The naïve implementation would seem to allocate a new promise for every iteration. However if the only requirement is that await schedule on the micro task scheduler, it seems to me to be intuitively possible to reuse a single function for each iteration. Do you see any reason why this would not be possible?

Nope, sounds good. This kind of thing is already being done in libraries, e.g. Bluebird uses some optimization techniques so that `yield`ing a promise is more efficient than `then`ing it because it avoids allocating any closures. I imagine very similar things could be done for async iterables.

> If this is the previous issue you are referring to (#22)
> 
> Can you give me an example in which executing an await synchronously would cause harm?

I was more referring to @zenparsing's answer in https://github.com/lukehoban/ecmascript-asyncawait/issues/16. 

In any case, I would definitely be interested in seeing an update to @zenparsing's numbers in e.g. the raw d8 shell, without Node's second event loop getting in the way. That should give a better idea of the performance bounds, although of course V8's promises are still one or two orders of magnitude slower than libraries like Bluebird and when.js, so we'd need to factor that in.

**Comment by jeffmo** [comment]
From #16: 

> Ah, you are of course correct; by using promises without await the optimization is observable.

As a thought experiment: What would the implications of having an async-await implementation that doesn't guarantee FIFO interop with promises be?

I'd note Hack as a reference point for sync-when-possible semantics: Hack executes async function synchronously ["until it returns normally, throws an error/exception, or reaches an await operation. [...] When an await operation executes, it checks the status of the dependency. If the result of the dependency is available, the await operation produces the result (without yielding control elsewhere) and the current async function continues executing."](https://github.com/hhvm/hack-langspec/blob/master/spec/15-functions.md#asynchronous-functions)

Of course Hack doesn't have to consider interop with an outside Promise-like abstraction, so that's one difference.

**Comment by jeffmo** [comment]
To come back to @zenparsing's example for purposes of the thought experiment: It does seem a bit odd to call `Promise.resolve()` within an async function when you could simply `await` it. The same goes for any indirect calls to `Promise.resolve()` (why call them without `await` if you're expecting a promise out of them within the body of the `async` function?)

**Comment by bterlson** [comment]
@jeffmo It is true, but I think with a slight tweak there is still an issue:

``` js
Promise.resolve(null).then(_=> console.log("1"));

async function bar() {
  var x = await foo;
  console.log("2");
} 
bar();
// 1, 2 without optimization
// 2, 1 with optimization
```

i'm not entirely sure that fifo ordering in these cases is super important, though. I would hope applications would not be sensitive to promise resolution handler ordering inside an async function and outside.

**Comment by zenparsing** [comment]
If await evaluated synchronously for "non-promises", then I believe it would be possible to synchronously inspect promises:

``` js
function inspect(promise) {

    let type = "", value;

    (async _=> {

        try { value = await promise; type = "normal"; }
        catch (x) { value = x; type = "error"; }

    })();

    if (type === "error")
        throw value;

    return { value, done: type !== "" };
}
```

Not sure how that bears on the question, but it's interesting...

**Comment by bterlson** [comment]
As of July TC39 meeting it is clear that synchronous await will have a very strong headwind in order to get consensus as even the most flattering view for synchronous await has some questionable corner cases/impossible to debug behavior. So we will continue with async-only await.

**Comment by jkroso** [comment]
I think the performance benefit of a cheap `await` would make it so much more useful since it can then be used fairly liberally. You could argue that that would lead to a significant reduction in bugs written by users. But then I know people have made a lot of arguments about the number of bugs this type of non-determinism can cause over the years. And I think on the style of programmer you are as to which arguments you favor. So I created a [poll](http://tally.tl/KAW0d). I think if 80% of programmers don't care about the edge cases then TC39 should allow them.
