### ISSUE TITLE
Can you new an async function?

### ISSUE THREAD

**Issue by bterlson** [tc39/proposal-async-await#42]
It might be nice to allow new on an async function and have it do something useful...

``` js
async function Person() {
  this.name = await getName();
}

// seems weird-ish.
var p = new Person();
p.then(person => console.log(person.name));


// but seems better in another async function
async function CreatePerson() {
  var person = await new Person();
  // ...
  return person;
}

// also allowing new argues for an additional async form:
class Foo {
    async constructor() { ... }
}
```

The behavior of generators is to allow new (IOW, all other function forms can be newed) which argues for allowing it. However, generators don't allow this in their body. This would be a needless restriction for async functions so I'm not sure it applies.

If anyone is aware of code today where new is expected to return a promise for an instance it would be a strong argument in favor of allowing new.

I think the only viable alternative is to make newing an async function an error.

**Comment by domenic** [comment]
> However, generators don't allow this in their body. This would be a needless restriction for async functions so I'm not sure it applies.

I don't quite follow. It seems to me that generators and async functions are pretty much exactly parallel in this situation. Both of them could allocate a `this`, which would be wrapped up in the returned object (as the generator's { done: true, value: theThis }, or the promise's fulfillment value). But generators chose to disallow `this` and allow `new`. Seems reasonable to do the same for async functions.

**Comment by bterlson** [comment]
IIRC the issue with generators was that people would expect this to be the generator instance but there were issues with making that the case (v8's implementation notwithstanding).

**Comment by domenic** [comment]
I mean, I would expect the `this` in an async function to be the promise instance. Same deal.

**Comment by bterlson** [comment]
But maybe without the same issues of calling .next on it and actually being useful in that the promise returned will have all added properties (unlike generator where this.foo = 1 wouldn't add foo until the generator instance was returned and resumed via .next())? Anyway, I just don't recall enough of the motivations for disallowing this in generators called with new to say whether it applies to async functions...

**Comment by domenic** [comment]
I guess all I'm saying is that I see more than the two options presented in your OP:
1. `this` refers to a newly-allocated object, which implicitly is the promise fulfillment value when there's no return-override. (I.e. we have the usual implicit `return this`, but since we're inside an async function, that means fulfill the returned promise with `this`.)
2. `this` refers to the to-be-returned promise instance itself.
3. `new` is allowed, but when used, `this` is a ReferenceError (like generators).
4. `new` is not allowed at all.

I think I prefer 3 > 4 > 1 >> 2.

I'm not too big of a fan of 1 because it breaks the expectation that `new X instanceof X`.

I can't think of any sensible way of relating 2 to the rest of the language. It's like... they're constructors, but they don't need to be called with `new`, and they're not related to prototypes? Would much rather get at the promise via some `function.promise` meta-property or similar.

**Comment by domenic** [comment]
On the other hand, 1 does give us a solution for the async constructor problem (seen today with e.g. createImageBitmap) by declaring the pattern to be "returns a promise for X when used with new". We say that this will get you a promise for a new X, derived from X.prototype.

If that gets traction, and especially given the nice syntax of `var x = await new X()`, maybe it is a good thing.

Seems a bit complicated with subclasses/super though.

Worth bringing up at TC39 maybe.

**Comment by bterlson** [comment]
2 is bogus IMO because no one would expect that behavior looking at aysnc function code (on top of being useless).

If we don't want newing an async function to do anything useful we can either make newing them an error or make newing them identical to calling except that referring to this is an error. I'd rather err on the conservative side and make it an error. I don't think the argument for alignment with generators is strong since they're really not the same thing. While the body might be a generator body if you squint, the thing you're actually calling or newing is not a generator function.

**Comment by domenic** [comment]
Yeah we can certainly loosen up later; I have no problem with 4 for now.

(I do think they're similar to generators though---special syntax for creating special return values. More "parallel" than "equal" or "a subset of", though.)

**Comment by RReverser** [comment]
Duplicating another possible way to solve this from Twitter discussion: https://gist.github.com/RReverser/d6a38095e4d3de6980e0

`new` can still create new instance with prototype of given function, but for async function it also adds `then` to the resulting object so that it's `await`-able at the same time (just implements Thenable interface).

**Comment by allenwb** [comment]
Are you going to allow async methods?  EG,

``` js
class Bar {
   async method() {return this.something}
   something(){...}
}
let bar = new Bar;
await bar.method();
```

If so, `new` within the async method needs to refer to object the method was invoked upon; just like with generator method.

**Comment by bterlson** [comment]
@allenwb Ahh yes this is sounding familiar now :) (I think you mean `this` not `new` above).

Yes, we def want async methods. Would it be ok to use the same semantics as we have today for normal methods? As in:

``` js
var obj = { async method() { } };
new obj.method(); // error due to obj.method not having [[Construct]]
```

**Comment by zenparsing** [comment]
My intuition is that `new` and `async` are mutually exclusive.  To me, `new` means allocation and initialization, which must be synchronous.  The downside is that in async-heavy contexts, you end up creating objects via static (async) factory methods:

``` js
    static async open(path, options) {
        path = Path.resolve(path);
        return new this(await File.openWrite(path), options);
    }
```

https://github.com/zenparsing/ziptar/blob/master/src/TarFile.js#L208-L212

**Comment by RReverser** [comment]
@zenparsing Please see https://github.com/tc39/ecmascript-asyncawait/issues/42#issuecomment-109420813 above. What do you think about such approach where allocation is still synchronous, prototype is preserved, but initialization is asynchronous? Should cover your usecase.

**Comment by zenparsing** [comment]
@RReverser Once we add inheritance though:

``` js
class A {
    async constructor(x) { return something }
}

class B extends A {
    async constructor() {
        let x = await foo();
        await super(x);
        this.y = "lskdjf";
    }
}
```

We can no longer have sync. allocation.  We could probably work around that, but it seems simpler to keep 'em separated.  I personally don't mind the async factory approach, after using it a bit.

There's also the issue of returning a partially initialized object from a constructor, which could break all kinds of invariants (for people who like that kind of thing).

**Comment by bterlson** [comment]
@zenparsing so you would be ok with [[Construct]] not being implemented on any async function?

**Comment by zenparsing** [comment]
@bterlson well, I would, fwiw.

**Comment by ljharb** [comment]
I agree with both https://github.com/tc39/ecmascript-asyncawait/issues/42#issuecomment-109435686 (no `[[Construct]]` on async functions, just like arrow functions), and with https://github.com/tc39/ecmascript-asyncawait/issues/42#issuecomment-109415171

I'd also suspect that @domenic's point 4 is the safest approach for now, since it leaves open the possibility in the future of loosening it after `async`/`await` has been in the wild for awhile.

**Comment by bterlson** [comment]
I'm going to move forward with no [[Construct]] for now (which is good, it's easy for me :)). I'll bring this up at TC-39 in July where we can discuss further.

**Comment by bterlson** [comment]
As of the July TC39 we have consensus on not giving async functions a [[construct]] slot.
