### ISSUE TITLE
Why is this in terms of generator objects?

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-async-await#49]
It's often cited that there's an isomorphism between async functions and generator functions. That makes sense, and I'd expect isomorphic control flow structures to be used.

However, this spec seems to directly use generator objects, %GeneratorPrototype%, methods named next and throw, and more. In fact, it seems to be transliterating the appendix's desugaring into ECMAspeak, from what I can tell.

This isn't really OK. Async functions and generators need to be separate, so that they can evolve divergently as necessary. There must be no dependency upon generators in the definition of async functions, but instead they should be their own state machine that does not reuse generator objects. This allows future extensions to be much more flexible, and implementations to be written in a more optimized fashion, by not exposing any internal machinery.

**Comment by domenic** [comment]
The "Evaluation of await expressions" section of http://www.microsoft.com/en-au/download/details.aspx?id=23753 gives an example of the kind of simplicity that can be achieved if you don't impose this intermediation layer of generators. Similarly the "Implementation example" gives the kind of expansion that implementers would be able to do if they weren't forced to create intermediate generators and wrappers thereof.

I think this would drastically simplify the spec, in the end. In fact it may be simple enough for me to do a PR.

**Comment by bterlson** [comment]
As far as I can tell, the current spec for async functions is just a more rigorous version of the C# spec. I am trying to stick to notational conventions of ECMAScript, and the easiest way to do that (since there are no ways in which async function and generator semantics diverge today) is by reusing the same machinery. But if you want to introduce a new way of describing semantics I suggest doing a PR so we have something concrete to discuss.

> and implementations to be written in a more optimized fashion, by not exposing any internal machinery.

The intention is that no internal machinery of the generator will be exposed. I think the only way it is now is by poisoning of %GeneratorPrototype% methods.

**Comment by zenparsing** [comment]
My inclination would be to more or less re-use the machinery already present for describing the behavior of generator functions (e.g. _generatorContext_).  However, It seems to me we might be better off calling `GeneratorResume` and `GeneratorResumeAbrupt` directly, instead of calling methods of the generator prototype.

What do you think?

**Comment by domenic** [comment]
I think this all gets much simpler if you don't try to reuse. The relevant machinery is simply the ability to pause and resume execution contexts. PR forthcoming to demonstrate; you'll see.

**Comment by bterlson** [comment]
> What do you think?

**Comment by bterlson** [comment]
> What do you think?

Yes, that's the right way to do it. I've pushed an update.
