### ISSUE TITLE
await one, two, three instead of await* [one, the, three]

### ISSUE THREAD

**Issue by trusktr** [tc39/proposal-async-await#81]
What about

``` js
await promise1, promise2, promise3

// or, formatted like like a multi-line single-var statement:

await promise1,
  promise2,
  promise3
```

?

Compare to the [previously proposed](https://github.com/tc39/ecmascript-asyncawait/issues/61) sugar for `Promise.all`:

``` js
await* [promise1, promise2, promise3]

// or

await* [ promise1,
  promise2,
  promise3
]
```

**Comment by inikulin** [comment]
There is no sugar for Promise.all anymore. Just use `await Promise.all`

**Comment by getify** [comment]
The `,` comma is the lowest on the operator precedence list, meaning everything else binds before it. Your suggestion would require `await` to bind less precedently than `,`, and I'm pretty sure that's not a good idea.

For example, someone could equally want:

``` js
var results = [await promise1, value2, promise3];
```

Your change would make this ambiguous... should it `await` all values in a comma list after it, or just the one?

And before you suggest `await (promise1, promise2, promise3)` instead, remember that `( .. , .. )` already has well-defined semantics, which is that only the last value in the list is the result of the`( .. )` expression evaluation.

**Comment by trusktr** [comment]
Maybe `async promise1, value2, promise3` would have to be a statement only, and not an expression?

But then that would limit it's use (no saving the values). I'm fine with Promise.all. :]

**Comment by getify** [comment]
just for posterity sake: the problem with `await * [ promise1, promise2, promise3 ]` (or just `await [ promise1, promise2, promise3 ]`) was that we'd be arbitrarily favoring `Promise.all( [ .. ] )` desugaring instead of `Promise.race( [ .. ] )`. Invariably, some would have wanted the former and some the latter.

I can't see any argument that makes one more appropriate than the other, so I don't think syntax would have been justified. Ultimately, that same dooming reasoning sinks this OP as well.
