### ISSUE TITLE
Clarifying question: can await be used in top-level code?

### ISSUE THREAD

**Issue by davidbau** [tc39/proposal-async-await#9]
In the proposal, it looks like "await" is to be used inside async functions.

Can "await" be used in top-level code?

The reason is, when teaching students, it makes a lot of sense to start with top-level code that does not contain function definitions, and it also makes sense to "await input", such as in this example using Iced CoffeeScript's "await".  What would this example look like in this proposal?

http://pencilcode.net/edit/guessmynumber

**Comment by lukehoban** [comment]
Summarizing where I think we are on this - there were three possible places we could deal with `await` in top-level code:
1. A JavaScript REPL
2. The ES6 `Script` [grammar](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-scripts)
3. The ES6 `Module` [grammar](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-modules)

I suggest that we update the proposal to include the semantics for (3) as an extension of the async module loader, and that we include an informative note on (1) that REPL's should aim to support `await` at top-level in a natural way for the REPL environment.  

I think we should not try to address (2) in the current proposal.

/cc @bterlson

**Comment by getify** [comment]
Speaking from the perspective of someone who teaches JS, I very much dislike that you would be creating yet another variation between normal JS and what the REPL does. Developers learn JS by trying things in REPLs (either CLI or in browser), and it's consistently confusing to them when they run across these various places where a REPL works differently from the global scope of a normal program.

There _are_ necessary differences, but we shouldn't be going out of our way to make more and more differences without really strong reason. I wrote [at length](http://blog.getify.com/dev-consoles-considered-harmful/) about this frustration.

In this case, I see no reason why we should encourage REPLs to diverge from the global script context. That is, if (2) isn't going to be handled, neither should (1). If (2) eventually gets handled in a later spec, like with `async do...` expressions, that should cover (1) as well.

**Comment by domenic** [comment]
REPLs should behave like modules, not scripts.

**Comment by arv** [comment]
This is getting off topic...

It is not that easy. You want the following to work:

```
> function f() { return 1; }
< undefined
> f()
< 1
```

if each line is a Script it works but if each line is a Module it does not.

**Comment by domenic** [comment]
Right, each line should not be a module, the entire REPL should be a module. Similarly, `var x = 5` should not create a global variable, and so on.

That said this is off topic indeed so I'll stop here.

**Comment by lukehoban** [comment]
@getify - I don't know of any way for `await` to work in top-level of scripts in a general way.  `async do` doesn't solve this, it is just sugar over a workaround (how to most easily put the code not at top-level).  So I don't think (2) is an option at all.

That leaves the question of whether you want to allow `await` in a REPL or not.  This isn't a spec question really - it's a question for various REPL implementers.  But my guess is they will want to support it just because it makes the REPL more useful and broadly usable.  Also, for better consistency with top level in modules, which will presumably be increasingly common.

**Comment by getify** [comment]
> include an informative note on (1) that REPL's should aim to support `await` at top-level

My objection was to including a note, and specifically to including a note (even a non-normative one) that says "should". If the spec doesn't aim to provide any guidance on _how_ (for REPLs), then it shouldn't aim to provide any guidance on _what_ (for REPLs) either. If a REPL wants to try it, having such a non-normative note in there isn't going to sway them one direction or the other.

---

Despite the assertion "the entire REPL should be a module", that's not in any way reflective of any real world requirement (or even present/near-future reality). Some REPLs will, I'm sure, but others won't. 

One problem with making a REPL session a module is that modules don't have access to the global scope, and yet many developers do in fact use things like the dev console's "REPL" to interact with the global scope. Same goes with interactive debugging sessions. Also, if a REPL has an `await` (or any other blocking mechanism, like `import`) in it, and the user types it in and it fires off a long running process, will that REPL just sit there appearing to be hung? I'm skeptical there really will be that many REPLs which go that direction, if for no other reason but UX.

My only point is that it's in no way a foregone conclusion that all or even most REPLs will significantly differ from main scripts in terms of how they deal with top-level asynchrony (blocking, etc). Since this spec doesn't want to tackle that beast, it should remain silent on the topic altogether.

**Comment by bterlson** [comment]
This was discussed at the July TC39. Await at top level introduces a large number of complexities with the module loader - complexities that need to be worked out there before they can be considered here. As such, TC39 wants to see async functions without await at top level. Await will still be reserved so we can pursue this in later editions of 262.

**Comment by pannous** [comment]
can't just the whole Top Level scope be marked async behind the scene?

**Comment by towerofnix** [comment]
@pannous I believe part of the problem is that in Node.js, scripts must be loaded and evaluated synchronously (no async) - because `require` is not an asynchronous function; it immediately returns the `module.exports` definition in the file path you give it.

I think it was discussed that, with ES6 modules, the top level scope *could* be marked async, because there is no "require function" - it's just a piece of syntax. But I haven't followed that discussion much, and I haven't taken much of a look at ES6 modules, so don't take my word for it!

**Comment by pannous** [comment]
@towerofnix interesting and good point. But what about the 'Script' context, wouldn't an async default be reasonable there?

**Comment by josephg** [comment]
Just to throw my hat in the ring - that this feature is blocked because of concerns about module loading is ridiculous. I don't care about the semantics of how `require` works. I *do* care about the code I write afterwards - eg:

```javascript
const fetch = require('node-fetch')

const someval = await fetch('https://my.example/someurl.json')
// Use someval.
```

Top-level await makes writing simple scripts like this 900% better, because I don't have to wrap all my code in a `(async () {})();` function block just to use all the features of the language.

**Comment by ljharb** [comment]
@josephg this repo is for the stage 4 proposal that landed in ES2017. You might be more interested in https://github.com/tc39/proposal-top-level-await ?

**Comment by josephg** [comment]
Ah, thanks!
